---
name: chart-pact-broker pipeline
trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: cnp-library
    type: github
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts'

variables:
  - name: agentPool
    value: ubuntu-latest

jobs:
- job: Validate
  pool:
    vmImage: ${{ variables.agentPool }}
  steps:
  - template: steps/charts/validate.yaml@cnp-library
    parameters:
      chartName: pact-broker
      chartReleaseName: chart-pact-broker-ci-test
      chartNamespace: chart-tests
      helmInstallTimeout: "180"
      helmDeleteWait: "10"

- job: Release
  # Make sure we have a tag to run this job
  condition: >
    and(
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      )
  dependsOn: Validate
  pool:
    vmImage: ${{ variables.agentPool }}
  steps:
  - template: steps/charts/release.yaml@cnp-library
    parameters:
      chartName: pact-broker
      chartReleaseName: chart-pact-broker
      chartNamespace: chart-tests
