ingressHost: pact-broker.platform.hmcts.net
databaseType: pod

postgresql:
  auth:
    username: "hmcts"
    password: "hmcts"
    database: "hmcts"
  primary:
    persistence:
      enabled: false
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 256Mi
  persistence:
    enabled: false

tags:
  postgresql-pod: true
