ingressHost: pact-broker.platform.hmcts.net
databaseType: pod

postgresql:
  postgresqlUsername: hmcts
  postgresqlPassword: hmcts
  postgresqlDatabase: hmcts
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 256Mi
  persistence:
    enabled: false

tags:
  postgresql-pod: true
