---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- ( include "labels" . ) | indent 4 }}
  annotations:
    {{- if eq .Values.enableTls true }}
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- else }}
    traefik.ingress.kubernetes.io/router.tls: "false"
    {{- end }}
    
spec:
  rules:
  - host: {{ required "ingressHost" .Values.ingressHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 80
