{{- if eq .Values.databaseType "external" }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}
spec:
  parameters:
    keyvaultName: {{ .Values.vaultName }}
    objects: |
      array:
        - |
          objectName: pact-db-user
          objectType: secret
        - |
          objectName: pact-db-password
          objectType: secret
    tenantId: {{ .Values.tenantId }}
    usePodIdentity: "true"
  provider: azure
{{- end }}
